### ISSUE TITLE
Add discuss.flarum.org url

### ISSUE THREAD

**Issue by luceos** [flagrow/bazaar#59]
We should allow the extra json part of the composer.json to hold a key that allows setting a value to point to the official thread over at discuss.flarum.org, we can then link to it from within bazaar.

**Comment by clarkwinkelmann** [comment]
This would be very useful. We should try to standardize that into the base Flarum developer guidelines as well.

Here's a suggestion:

```
{
    "extra": {
        "flarum-extension": {
            "title": "Flagrow Bazaar",
            "icon": {
                "name": "shopping-bag",
                "backgroundColor": "#000",
                "color": "#87d37c"
            },
            "discuss_link": "https://discuss.flarum.org/d/5151-flagrow-bazaar-the-extension-marketplace"
        }
    }
}
```

**Comment by clarkwinkelmann** [comment]
Bumping this. I think it's time we take a decision.

In order not to mess with future Flarum breaking changes I think we might want to use our own `extra` key. Could be `bazaar` or `flagrow` (the latter sounds better because it's actually flagrow.io that will crunch this data).

We could take the opportunity to standardize a few other keys so extension developer can prepare themselves for the future flagrow.io update that will finally add better package descriptions.

I suggest something like this:

```
{
    "extra": {
        "flagrow": {
            "discuss": "https://discuss.flarum.org/d/5151-flagrow-bazaar-the-extension-marketplace",
            "screenshots": [
                {
                    "url": "https://discuss.hyn.me/assets/bazaar.gif",
                    "label": "Bazaar in action"
                }
            ]
        }
    }
}
```

Other keys I think could be added:

`latest_flarum_version` or something: the latest flarum version tested by the extension developer. Could be used to show extensions "not yet marked compatible by the creator" even if they can technically be updated

`description_file` or something: a link to a markdown resource we should show as an extended description. If we do show a description I think we will default to the GitHub or GitLab README so this might not be very useful. But it could be used to use a shorter description without all the build badges and install instructions.

The most useful of all for the moment would still be `discuss`. It could also be useful for our internal tool discussed in https://github.com/gravure/org/issues/41

**Comment by luceos** [comment]
Agreed with your proposal. But let's only use the keys you added in your example for now 👍
