### ISSUE TITLE
Need a Token please

### ISSUE THREAD

**Issue by hamalrad** [flagrow/bazaar#78]
Hi,
I've installed Flarum and Bazaar using [pockethold](https://discuss.flarum.org/d/5731-pockethold-a-web-based-installer) and don't have a token.
How can I get a token?
Thank you

**Comment by luceos** [comment]
Hello @hamalrad in theory Flarum should retrieve a new token whenever it has none. Can you check in the settings modal of Bazaar (extensions tab of Flarum, tripple dot next to the extension name) whether the field is still blank after refreshing your page?

**Comment by hamalrad** [comment]
Yup... still blank

**Comment by luceos** [comment]
Hi, so we discussed this at length and we foresee troubles with retrieving the list of extensions even if we generate a token for you to use. Instead we'd like to trace the cause of not having a token in the first place, because it points at not having a connection to the internet.

Is that a correct assumption? If your connection is stable, would you be able to provide me with your IP address so I can check our access logs for incoming requests.

**Comment by luceos** [comment]
@hamalrad i just confirmed this is a bug, no need to do anything.

**Comment by luceos** [comment]
http://oauth2.thephpleague.com/v5-security-improvements/

**Comment by luceos** [comment]
Relates to https://github.com/laravel/passport/issues/432

Patch incoming. No need to do anything.

**Comment by hamalrad** [comment]
Well, i don't know what you did - but I now have a token.
Thanks!

**Comment by luceos** [comment]
@hamalrad good to hear and thanks for letting us know. If you have any other troubles you know where to find us :grin:
