### ISSUE TITLE
Extension Logo Bazaar

### ISSUE THREAD

**Issue by luceos** [flagrow/bazaar#99]
It's time we profesionalised this extension a bit more. For Bazaar we need;

- svg
- 120x120 is used inside Flarum
- flagrow.io (for now) uses 60x60

Migrated from #84

**Comment by darisi** [comment]
Here are some variations of the Bazaar logo. Works nicely with the "Marketplace" functionality as well. I think that #6 is the best one here as it's clear and simple. Adding some fruit or a person makes it more like an illustration instead of an icon/symbol.

Also as a note the style here (lines + white opacity fill). Will be also used for other logos/symbols like Masquerade so we consistency between our things.
 
<img width="570" alt="bazaar-logos" src="https://user-images.githubusercontent.com/6051129/33242875-9e0a7acc-d2db-11e7-9e96-d7cf0b566e75.png">

**Comment by clarkwinkelmann** [comment]
I think 6 or 7 will render better when they are small. My favorite is 6 as well @darisi .

I find the color combination between the logo and the text very strange...

**Comment by luceos** [comment]
The variants with striping are best. My favorite was actually 1, but I can see that 6 is better for rendering too.

**Comment by Ralkage** [comment]
6 (even though the pattern on the logo(the tarp?) brings in the main focus) but 7 makes me look at the entire logo from the icon to the text.

Do you plan on using the icon as the actual extension image for the Extensions page?

**Comment by darisi** [comment]
Thanks, everyone for the help. Some good points there. Redid the Bazaar one and created the logos for other extensions.

I think this style will work really well for our premium extensions. I actually like the ones that are on the white background + have a bit of blue in them the best.

Did I use the Mason one ok? Bricks as in custom fields that you put together. But I don't know if they look the best on the purple background which we may use on the flagrow site. I may tweak the line width for these a bit, which should improve them. Unless we just use the white ones.

[logos1.pdf](https://github.com/flagrow/bazaar/files/1525052/logos1.pdf)
[logos2.pdf](https://github.com/flagrow/bazaar/files/1525053/logos2.pdf)

**Comment by luceos** [comment]
I really, really love these. Except for the Byobu one (also note it's officially byōbu), because it now looks like a map, but it's in fact a privacy screen, like this:

![image](https://user-images.githubusercontent.com/504687/33529093-f2bbddbe-d86b-11e7-9512-afd6bc78cd6a.png)

**Comment by darisi** [comment]
Will ad some more detail to make it byobu better :)

**Comment by existo** [comment]
I prefer the right versions but they look really good. Nice job @darisi !

**Comment by darisi** [comment]
Updated the logos/extension pages - Full view (just use right/left to scroll through them) - https://invis.io/YZAYHTHK7#/259671208_icon-Bazaar

Here's a small preview as well.
<img width="929" alt="screen shot 2017-12-17 at 13 01 23" src="https://user-images.githubusercontent.com/6051129/34079259-83e28086-e32a-11e7-9025-f8e7c58bc671.png">

I've also tested the version where the logos have a blue element in them, but they didn't work well when they were small etc. So The lighter whites were the way to go.

Added also some images for the extension but some may need changing.

**Comment by luceos** [comment]
Looking good @darisi can we get them added to the design repo for further processing? If you do (as svg at least) we can pick them up for the upcoming release 🤤

**Comment by clarkwinkelmann** [comment]
Looks good !

I find a bit disturbing that the icons seem to be more related to the name than the purpose of the extension. From the icons alone it makes me think Masquerade is a privacy/anonymous extension of some kind and Byobu some kind of paywall :hankey: Mason is also a bit strange in that sense.

The background image for Byobu is really useful to show what the icon is supposed to represent. I still think it's a map otherwise :innocent:

**Comment by luceos** [comment]
Oh totally didn't see that, Byobu still isn't a privacy screen..

**Comment by luceos** [comment]
@darisi misposted the following https://github.com/flagrow/bazaar/issues/84#issuecomment-355840241

**Comment by luceos** [comment]
@darisi I'm missing a SVG variant SYMBOL for MASON.

**Comment by darisi** [comment]
@luceos pushed a commit. It was there It was just named "icon" instead of "symbol" fixed all of these now.

**Comment by jordanjay29** [comment]
These look great!
